/**
 * Natural Query Panel Component
 * 
 * Provides an interface for users to ask questions in natural language
 * and get SQL queries generated by the Natural-SQL backend.
 */

import { useState, useEffect, useRef } from 'react';
import styled from 'styled-components';
import { generateSQL, checkHealth, APIError } from '../services/api';

const PanelContainer = styled.div`
  display: flex;
  flex-direction: column;
  height: 100%;
  background-color: ${({ theme }) => theme.background};
  overflow: hidden;
`;

const PanelHeader = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 16px;
  background: ${({ theme }) => theme.isDarkMode 
    ? 'linear-gradient(135deg, rgba(76, 175, 80, 0.1), rgba(33, 150, 243, 0.1))' 
    : 'linear-gradient(135deg, rgba(76, 175, 80, 0.05), rgba(33, 150, 243, 0.05))'};
  border-bottom: 1px solid ${({ theme }) => theme.border};
`;

const HeaderTitle = styled.div`
  display: flex;
  align-items: center;
  gap: 10px;
  font-weight: 600;
  font-size: 14px;
  color: ${({ theme }) => theme.text.primary};

  svg {
    color: ${({ theme }) => theme.primary};
  }
`;

const StatusIndicator = styled.div`
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 12px;
  color: ${({ theme }) => theme.text.secondary};
`;

const StatusDot = styled.div`
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background-color: ${({ $status, theme }) => 
    $status === 'healthy' ? '#22c55e' : 
    $status === 'checking' ? '#f59e0b' : '#ef4444'};
  box-shadow: 0 0 8px ${({ $status }) => 
    $status === 'healthy' ? 'rgba(34, 197, 94, 0.5)' : 
    $status === 'checking' ? 'rgba(245, 158, 11, 0.5)' : 'rgba(239, 68, 68, 0.5)'};
  animation: ${({ $status }) => $status === 'checking' ? 'pulse 2s ease-in-out infinite' : 'none'};

  @keyframes pulse {
    0%, 100% { opacity: 1; }
    50% { opacity: 0.5; }
  }
`;

const ContentArea = styled.div`
  flex: 1;
  padding: 16px;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 16px;

  &::-webkit-scrollbar {
    width: 6px;
  }

  &::-webkit-scrollbar-track {
    background: transparent;
  }

  &::-webkit-scrollbar-thumb {
    background: ${({ theme }) => 
      theme.isDarkMode ? 'rgba(255, 255, 255, 0.2)' : 'rgba(0, 0, 0, 0.2)'};
    border-radius: 3px;
  }
`;

const InputSection = styled.div`
  display: flex;
  flex-direction: column;
  gap: 8px;
`;

const Label = styled.label`
  font-size: 13px;
  font-weight: 500;
  color: ${({ theme }) => theme.text.primary};
  display: flex;
  align-items: center;
  gap: 6px;
`;

const QuestionInput = styled.input`
  width: 100%;
  padding: 12px 16px;
  border-radius: 8px;
  border: 2px solid ${({ theme }) => theme.border};
  background-color: ${({ theme }) => theme.surface};
  color: ${({ theme }) => theme.text.primary};
  font-size: 14px;
  transition: all 0.2s ease;
  box-sizing: border-box;

  &:focus {
    outline: none;
    border-color: ${({ theme }) => theme.primary};
    box-shadow: 0 0 0 3px ${({ theme }) => theme.primary}20;
  }

  &::placeholder {
    color: ${({ theme }) => theme.text.disabled};
  }

  &:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }
`;

const SchemaPreview = styled.div`
  padding: 12px;
  background: ${({ theme }) => theme.surface};
  border: 1px solid ${({ theme }) => theme.border};
  border-radius: 6px;
  font-family: 'Roboto Mono', monospace;
  font-size: 12px;
  color: ${({ theme }) => theme.text.secondary};
  max-height: 120px;
  overflow-y: auto;
  white-space: pre-wrap;
  word-break: break-word;

  &::-webkit-scrollbar {
    width: 4px;
  }

  &::-webkit-scrollbar-thumb {
    background: ${({ theme }) => theme.border};
    border-radius: 2px;
  }
`;

const ActionButtons = styled.div`
  display: flex;
  gap: 8px;
  align-items: center;
`;

const GenerateButton = styled.button`
  flex: 1;
  padding: 12px 20px;
  background: ${({ theme }) => theme.primary};
  color: white;
  border: none;
  border-radius: 6px;
  font-size: 14px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s ease;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;

  &:hover:not(:disabled) {
    background: ${({ theme }) => theme.primaryHover};
    transform: translateY(-1px);
    box-shadow: 0 4px 12px ${({ theme }) => theme.primary}40;
  }

  &:active:not(:disabled) {
    transform: translateY(0);
  }

  &:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  svg {
    width: 16px;
    height: 16px;
  }
`;

const ClearButton = styled.button`
  padding: 12px 20px;
  background: transparent;
  color: ${({ theme }) => theme.text.secondary};
  border: 1px solid ${({ theme }) => theme.border};
  border-radius: 6px;
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s ease;

  &:hover {
    background: ${({ theme }) => theme.hover};
    border-color: ${({ theme }) => theme.text.secondary};
  }
`;

const ResultSection = styled.div`
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 16px;
  background: ${({ theme }) => theme.surface};
  border: 1px solid ${({ theme }) => theme.border};
  border-radius: 8px;
  animation: slideIn 0.3s ease-out;

  @keyframes slideIn {
    from {
      opacity: 0;
      transform: translateY(-10px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }
`;

const ResultHeader = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding-bottom: 8px;
  border-bottom: 1px solid ${({ theme }) => theme.border};
`;

const ResultTitle = styled.div`
  font-size: 13px;
  font-weight: 600;
  color: ${({ theme }) => theme.text.primary};
  display: flex;
  align-items: center;
  gap: 6px;

  svg {
    color: ${({ theme }) => theme.success};
  }
`;

const CopyButton = styled.button`
  padding: 6px 12px;
  background: transparent;
  color: ${({ theme }) => theme.text.secondary};
  border: 1px solid ${({ theme }) => theme.border};
  border-radius: 4px;
  font-size: 12px;
  cursor: pointer;
  transition: all 0.2s ease;
  display: flex;
  align-items: center;
  gap: 4px;

  &:hover {
    background: ${({ theme }) => theme.hover};
    border-color: ${({ theme }) => theme.primary};
    color: ${({ theme }) => theme.primary};
  }

  svg {
    width: 14px;
    height: 14px;
  }
`;

const SQLDisplay = styled.pre`
  padding: 12px;
  background: ${({ theme }) => theme.isDarkMode ? '#1e1e1e' : '#f5f5f5'};
  border: 1px solid ${({ theme }) => theme.border};
  border-radius: 6px;
  font-family: 'Roboto Mono', monospace;
  font-size: 13px;
  color: ${({ theme }) => theme.text.primary};
  overflow-x: auto;
  margin: 0;
  white-space: pre-wrap;
  word-break: break-word;
`;

const UseQueryButton = styled.button`
  width: 100%;
  padding: 10px 16px;
  background: ${({ theme }) => theme.secondary};
  color: white;
  border: none;
  border-radius: 6px;
  font-size: 13px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s ease;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;

  &:hover {
    background: ${({ theme }) => theme.secondaryHover};
    transform: translateY(-1px);
  }

  svg {
    width: 14px;
    height: 14px;
  }
`;

const ErrorMessage = styled.div`
  padding: 12px 16px;
  background: ${({ theme }) => theme.isDarkMode ? 'rgba(239, 68, 68, 0.1)' : 'rgba(239, 68, 68, 0.05)'};
  border: 1px solid rgba(239, 68, 68, 0.3);
  border-radius: 6px;
  color: #ef4444;
  font-size: 13px;
  display: flex;
  align-items: flex-start;
  gap: 8px;
  animation: slideIn 0.3s ease-out;

  svg {
    flex-shrink: 0;
    margin-top: 2px;
  }
`;

const LoadingOverlay = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 12px;
  padding: 32px;
  text-align: center;
  color: ${({ theme }) => theme.text.secondary};

  svg {
    animation: spin 2s linear infinite;
  }

  @keyframes spin {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
  }
`;

const HintText = styled.div`
  font-size: 12px;
  color: ${({ theme }) => theme.text.disabled};
  font-style: italic;
  margin-top: 4px;
`;

const ExampleQuestions = styled.div`
  display: flex;
  flex-direction: column;
  gap: 8px;
  margin-top: 8px;
`;

const ExampleButton = styled.button`
  padding: 8px 12px;
  background: ${({ theme }) => theme.hover};
  color: ${({ theme }) => theme.text.secondary};
  border: 1px solid ${({ theme }) => theme.border};
  border-radius: 6px;
  font-size: 12px;
  text-align: left;
  cursor: pointer;
  transition: all 0.2s ease;

  &:hover {
    background: ${({ theme }) => theme.surface};
    color: ${({ theme }) => theme.text.primary};
    border-color: ${({ theme }) => theme.primary};
  }
`;

const NaturalQueryPanel = ({ 
  schema, 
  onUseQuery,
  onGenerateComplete 
}) => {
  const [question, setQuestion] = useState('');
  const [generatedSQL, setGeneratedSQL] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [backendStatus, setBackendStatus] = useState('checking');
  const [copied, setCopied] = useState(false);
  const questionInputRef = useRef(null);

  // Check backend health on mount and periodically
  useEffect(() => {
    const checkBackendHealth = async () => {
      try {
        await checkHealth();
        setBackendStatus('healthy');
      } catch (err) {
        setBackendStatus('unhealthy');
      }
    };

    checkBackendHealth();
    const interval = setInterval(checkBackendHealth, 30000); // Check every 30s
    return () => clearInterval(interval);
  }, []);

  // Focus question input on mount
  useEffect(() => {
    if (questionInputRef.current) {
      questionInputRef.current.focus();
    }
  }, []);

  const handleGenerate = async () => {
    if (!question.trim()) {
      setError('Please enter a question');
      return;
    }

    if (!schema || !schema.trim()) {
      setError('Database schema is not available. Please ensure you have a database connection.');
      return;
    }

    setLoading(true);
    setError(null);
    setGeneratedSQL(null);

    try {
      const result = await generateSQL(schema, question);
      setGeneratedSQL(result.sql_query);
      
      if (onGenerateComplete) {
        onGenerateComplete(result.sql_query, question);
      }
    } catch (err) {
      if (err instanceof APIError) {
        setError(`${err.message}`);
      } else {
        setError(`Failed to generate SQL: ${err.message}`);
      }
    } finally {
      setLoading(false);
    }
  };

  const handleClear = () => {
    setQuestion('');
    setGeneratedSQL(null);
    setError(null);
    if (questionInputRef.current) {
      questionInputRef.current.focus();
    }
  };

  const handleCopySQL = async () => {
    if (generatedSQL) {
      try {
        await navigator.clipboard.writeText(generatedSQL);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } catch (err) {
        console.error('Failed to copy:', err);
      }
    }
  };

  const handleUseQuery = () => {
    if (generatedSQL && onUseQuery) {
      onUseQuery(generatedSQL, question);
    }
  };

  const handleExampleClick = (exampleQuestion) => {
    setQuestion(exampleQuestion);
    if (questionInputRef.current) {
      questionInputRef.current.focus();
    }
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && !loading) {
      handleGenerate();
    }
  };

  const exampleQuestions = [
    'Show me all users who registered in the last month',
    'What are the top 5 best selling products?',
    'Calculate total revenue by product category',
    'Find customers who have never placed an order',
  ];

  return (
    <PanelContainer>
      <PanelHeader>
        <HeaderTitle>
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M13 2L3 14h8l-1 8 10-12h-8l1-8z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
          Natural Query
        </HeaderTitle>
        <StatusIndicator>
          <StatusDot $status={backendStatus} />
          <span>{backendStatus === 'healthy' ? 'AI Ready' : backendStatus === 'checking' ? 'Checking...' : 'AI Offline'}</span>
        </StatusIndicator>
      </PanelHeader>

      <ContentArea>
        <InputSection>
          <Label>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
            Ask a Question
          </Label>
          <QuestionInput
            ref={questionInputRef}
            type="text"
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            onKeyPress={handleKeyPress}
            placeholder="Example: Show me all users who registered this month"
            disabled={loading || backendStatus !== 'healthy'}
          />
          <HintText>Press Enter to generate SQL query</HintText>
        </InputSection>

        {!generatedSQL && !loading && !error && (
          <ExampleQuestions>
            <Label style={{ fontSize: '12px' }}>Try these examples:</Label>
            {exampleQuestions.map((example, index) => (
              <ExampleButton key={index} onClick={() => handleExampleClick(example)}>
                {example}
              </ExampleButton>
            ))}
          </ExampleQuestions>
        )}

        <InputSection>
          <Label>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M4 7v10c0 2 1 3 3 3h10c2 0 3-1 3-3V7c0-2-1-3-3-3H7C5 4 4 5 4 7z" stroke="currentColor" strokeWidth="2"/>
              <path d="M9 4v16M4 15h16" stroke="currentColor" strokeWidth="2"/>
            </svg>
            Database Schema
          </Label>
          <HintText>The full schema is now available in the left sidebar under Database Schema.</HintText>
        </InputSection>

        <ActionButtons>
          <GenerateButton onClick={handleGenerate} disabled={loading || backendStatus !== 'healthy'}>
            {loading ? (
              <>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="3" opacity="0.25"/>
                  <path d="M12 2a10 10 0 0 1 10 10" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/>
                </svg>
                Generating...
              </>
            ) : (
              <>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M13 2L3 14h8l-1 8 10-12h-8l1-8z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
                Generate SQL
              </>
            )}
          </GenerateButton>
          <ClearButton onClick={handleClear} disabled={loading}>
            Clear
          </ClearButton>
        </ActionButtons>

        {loading && (
          <LoadingOverlay>
            <svg width="40" height="40" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="3" opacity="0.25"/>
              <path d="M12 2a10 10 0 0 1 10 10" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/>
            </svg>
            <div>AI is generating your SQL query...</div>
            <div style={{ fontSize: '12px', opacity: 0.7 }}>This may take a few seconds</div>
          </LoadingOverlay>
        )}

        {error && (
          <ErrorMessage>
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
            <div>{error}</div>
          </ErrorMessage>
        )}

        {generatedSQL && (
          <ResultSection>
            <ResultHeader>
              <ResultTitle>
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                </svg>
                Generated SQL Query
              </ResultTitle>
              <CopyButton onClick={handleCopySQL}>
                {copied ? (
                  <>
                    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" stroke="currentColor" strokeWidth="2"/>
                    </svg>
                    Copied!
                  </>
                ) : (
                  <>
                    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" stroke="currentColor" strokeWidth="2"/>
                    </svg>
                    Copy
                  </>
                )}
              </CopyButton>
            </ResultHeader>
            <SQLDisplay>{generatedSQL}</SQLDisplay>
            <UseQueryButton onClick={handleUseQuery}>
              <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
              Use This Query in Editor
            </UseQueryButton>
          </ResultSection>
        )}
      </ContentArea>
    </PanelContainer>
  );
};

export default NaturalQueryPanel;

